"""Feedback update

Revision ID: 0003
Revises: 0002
Create Date: 2023-10-01 21:00:31.978906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'feedback_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('feedback_type', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
