"""Feedback update

Revision ID: 0005
Revises: 0004
Create Date: 2023-10-13 08:54:51.769844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'pinned_msg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('pinned_msg_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
