"""city changes

Revision ID: 2
Revises: 1
Create Date: 2022-10-10 21:58:55.928658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sinoptik_url', sa.TEXT(), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('sinoptik_url')
        batch_op.drop_column('local_name')

    # ### end Alembic commands ###
