"""crypto_watchlist

Revision ID: 3
Revises: 2
Create Date: 2022-08-07 14:19:01.228324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3'
down_revision = '2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_currency',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('abbr', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crypto_currency_watchlist',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('crypto_currency_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['crypto_currency_id'], ['crypto_currency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'crypto_currency_id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crypto_currency_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'crypto_currency', ['crypto_currency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('crypto_currency_id')

    op.drop_table('crypto_currency_watchlist')
    op.drop_table('crypto_currency')
    # ### end Alembic commands ###
