"""changed_timezones

Revision ID: 5
Revises: 4
Create Date: 2022-08-10 10:59:03.731415

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5'
down_revision = '4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone_offset', sa.INTEGER(), nullable=True))
        batch_op.alter_column('lat',
                              existing_type=sa.REAL(),
                              nullable=True)
        batch_op.alter_column('lon',
                              existing_type=sa.REAL(),
                              nullable=True)
        batch_op.alter_column('url',
                              existing_type=sa.TEXT(),
                              nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone_offset', sa.INTEGER(), nullable=True))
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_column('timezone_offset')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.alter_column('url',
                              existing_type=sa.TEXT(),
                              nullable=False)
        batch_op.alter_column('lon',
                              existing_type=sa.REAL(),
                              nullable=False)
        batch_op.alter_column('lat',
                              existing_type=sa.REAL(),
                              nullable=False)
        batch_op.drop_column('timezone_offset')

    # ### end Alembic commands ###
