"""city_to_user

Revision ID: c9aaf13d64fa
Revises: 23da2158d4a7
Create Date: 2023-02-26 16:56:33.801260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9aaf13d64fa'
down_revision = '23da2158d4a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'city', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.drop_column('city', 'user_id')
    # ### end Alembic commands ###
